spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 120MB
      enabled: true

  # Security OAuth
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: ${REDIRECT_URI}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        # Provider 설정
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

logging.level:
  org.hibernate.SQL: debug
  org.springframework.web: trace
  #  org.apache: trace
  org.hibernate.type: trace

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME}

cors:
  allowed-origins: ${FRONT_URL}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
    tokenExpiration: ${EXPIRATION_TIME}
    refreshTokenExpiration: ${REFRESH_EXPIRATION_TIME}
  cors:
    allowedOrigins: ${FRONT_URL},http://localhost:8080
  oauth2:
    authorizedRedirectUris: ${FRONT_URL}