spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/triprint
    username: root
    password: .:zpWdv9803@
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    # Security OAuth
    security:
      oauth2.client:
        registration:
          kakao:
            clientId: '355bc84f673d4cd4b5d9c1b88838cf32'
            clientSecret: ${CLIENT_SECRET}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:3000/auth/sign-in"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        # Provider 설정
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id




logging.level:
  org.hibernate.SQL: debug
  org.springframework.web: trace
#  org.apache: trace
  org.hibernate.type: trace